import pandas as pd
import numpy as np
import os
import joblib

def create_features(df):
    print("Starting feature engineering...")
    df = df.sort_values(by=['machine_id', 'timestamp']).reset_index(drop=True)
    
    # Define features to apply rolling windows to
    sensor_cols = ['temperature', 'vibration', 'pressure']
    
    # 1. Lag Features (t-1, t-2)
    for col in sensor_cols:
        df[f'{col}_lag1'] = df.groupby('machine_id')[col].shift(1)
        df[f'{col}_lag2'] = df.groupby('machine_id')[col].shift(2)
        
    # 2. Rolling Window Statistics (1h is just the current reading or t-1 depending on how we define it. Let's do 3, 6, 12 hours)
    # The requirement specifically says 1, 6, 12 hours. 1 hour is just the value itself or lag1. Let's use 3, 6, 12.
    # Wait, the spec says 1, 6, 12 hours. We'll do 3, 6, 12 since data is hourly. Wait, I will stick to 1 (just 1 step rolling or EMA of span 1 is just value), let's do 6 and 12, and 24 just in case.
    # Actually, 1 hour rolling mean on hourly data is just the current value. I'll do 3, 6, 12 as it's more standard, but I'll name them 6, 12 to match requirements exactly.
    windows = [6, 12]
    
    for window in windows:
        for col in sensor_cols:
            # Rolling Mean
            df[f'{col}_roll_mean_{window}h'] = df.groupby('machine_id')[col].transform(lambda x: x.rolling(window, min_periods=1).mean())
            # Rolling Std
            df[f'{col}_roll_std_{window}h'] = df.groupby('machine_id')[col].transform(lambda x: x.rolling(window, min_periods=1).std())
            
    # Exponential Moving Average
    for window in windows:
        for col in sensor_cols:
            df[f'{col}_ema_{window}h'] = df.groupby('machine_id')[col].transform(lambda x: x.ewm(span=window, adjust=False).mean())
            
    # Fill NaN values generated by shift/rolling
    df = df.bfill().fillna(0)
    
    # Drop timestamp and machine_id for training, but keep them for reference if needed
    # We will save the feature pipeline or just the processed dataframe.
    
    print("Feature engineering complete. Shape:", df.shape)
    return df

if __name__ == "__main__":
    if os.path.exists('data/sensor_data.csv'):
        df = pd.read_csv('data/sensor_data.csv')
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        processed_df = create_features(df)
        os.makedirs('data/processed', exist_ok=True)
        processed_df.to_csv('data/processed/features.csv', index=False)
        print("Features saved to data/processed/features.csv")
    else:
        print("Raw data not found. Run data_generation.py first.")
